linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 120
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/go-faster/
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - exitAfterDefer
      - whyNoLint
      - singleCaseSwitch
      - commentedOutCode
      - appendAssign
      - unnecessaryBlock
      - redundantSprint

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Breaks with buildssa error for some reason.
    #- unparam

    # Do not enable:
    # - wsl       (too opinionated about newlines)
    # - godox     (todos are OK)
    # - bodyclose (false positives on helper functions)
    # - prealloc  (not worth it in scope of this project)
    # - maligned  (same as prealloc)
    # - funlen    (gocyclo is enough)
    # - gochecknoglobals (we know when it is ok to use globals)
    # - gochecknoinits (we know when it is ok to use inits)
    # - dupl (too opinionated)

issues:
  exclude-use-default: false
  exclude-rules:
    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - lll

    # Ignore shadowing of err.
    - linters: [govet]
      text: 'declaration of "(err|ctx|log|c)"'

    # Ignore linters in main packages.
    - path: main\.go
      linters: [goconst, funlen, gocognit, gocyclo]

    # Ignore false-positive in test.
    - linters: [unused]
      text: "(type|field) `i` is unused"
      file: 'yson/bugs_test\.go'

    # Ignore error check in defer.
    - linters: [errcheck]
      source: 'defer .*\.(Close|Abort)\(\)'

    # Allow old protobuf.
    - linters: [staticcheck]
      text: 'SA1019: "github.com/golang/protobuf/proto" is deprecated.*'
